"""Prompt composition helpers for skill execution."""

from __future__ import annotations

from src.skills.skill_models import Skill


def compose_skill_prompt(
    skill: Skill,
    workspace: str,
    user_prompt: str,
    payload_json: str,
) -> str:
    """Compose the legacy single-shot skill prompt."""
    return (
        f"# Agent Skill: {skill.name} ({skill.frontmatter.version})\n"
        f"Active workspace: {workspace}\n\n"
        "## Skill Instructions\n"
        f"{skill.body_md.strip()}\n\n"
        "## Workspace Briefing Book (JSON)\n"
        "This briefing book is the authoritative source of truth for the "
        "active RFP workspace. It contains four sections:\n"
        "  * `entities`           — typed entities (each carries `source_chunks`)\n"
        "  * `source_chunks`      — verbatim RFP text blocks (quote from these)\n"
        "  * `relationships`      — typed KG edges between entities\n"
        "  * `retrieval_metadata` — how this slice was selected (chat-grade\n"
        "    hybrid retrieval vs. bulk fallback); use it to gauge coverage.\n\n"
        "### Citation Discipline (MANDATORY)\n"
        "When you reference a requirement, deliverable, clause, "
        "`proposal_instruction` (UCF Section L or equivalent — e.g. an "
        "\"Instructions to Offerors\" section in a FAR 16 task order, FOPR, "
        "BPA call, OTA, or agency-specific format), `evaluation_factor` "
        "(UCF Section M or equivalent — e.g. \"Evaluation Criteria\", "
        "adjectival rating scheme, or LPTA basis), or any other RFP "
        "obligation:\n"
        "  1. **Quote verbatim** from the matching `source_chunks[*].content` — "
        "never paraphrase the RFP wording.\n"
        "  2. **Cite the chunk_id inline** in the form `[chunk-xxxxxxxx]` so "
        "the reader can trace any claim back to the source document.\n"
        "  3. If a needed source chunk is missing from the briefing book, "
        "emit a `GAP` marker rather than fabricating language.\n"
        "  4. Use the `relationships` block to confirm "
        "`proposal_instruction` ↔ `evaluation_factor` ↔ `requirement` "
        "traceability — do not invent links the KG does not show.\n\n"
        "### Coverage Discipline (Phase 1.6)\n"
        "The briefing book was assembled by chat-grade hybrid retrieval over "
        "the user request + skill description. Treat it as the *complete* "
        "evidence set for this invocation:\n"
        "  * Do **not** invent entities, factors, requirements, deliverables, "
        "or clauses that are absent from the briefing book.\n"
        "  * **This solicitation may use UCF or non-UCF format.** Map to the "
        "actual `proposal_instruction` and `evaluation_factor` entities "
        "regardless of section heading. Only emit `GAP` when no matching "
        "instruction or evaluation criterion exists *anywhere* in the "
        "briefing book — never because the entity lacks a literal \"Section "
        "L\" or \"Section M\" label. Many federal task orders, FOPRs, BPA "
        "calls, and OTAs put instructions inline in the PWS or in named "
        "attachments.\n"
        "  * If the user asks about a topic that is not represented in the "
        "`entities` / `source_chunks` blocks (check `retrieval_metadata` for "
        "coverage signals like low `matched_entities`), say so explicitly with "
        "`GAP: insufficient retrieval coverage for <topic>` instead of "
        "substituting unrelated content from another factor or section.\n"
        "  * Stay inside the slice. If the user asks for the small business "
        "participation outline, do not bleed in cybersecurity, transition, or "
        "other factors unless the briefing book actually surfaces them.\n\n"
        "```json\n"
        f"{payload_json}\n"
        "```\n\n"
        "## User Request\n"
        f"{user_prompt.strip() if user_prompt.strip() else '(use skill defaults)'}\n\n"
        "## Output\n"
        "Follow the skill's Output Contract section exactly. If a JSON "
        "envelope is specified, return only the JSON envelope. Inline "
        "chunk-ID citations are required wherever you quote RFP text.\n"
    )